volumes:
  pg_data:
  media:
  static:
  frontend_build:

services:

  db:
    container_name: foodgram-db
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    container_name: foodgram-backend
    build: ../backend
    volumes:
      - ../backend/:/app/
      - media:/app/media/
      - static:/app/static/
    depends_on:
      - db
    env_file:
      - ../backend/.env

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - frontend_build:/app/build_output

  proxy:
    image: nginx:1.25.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/var/html/media/
      - static:/var/html/static/
    depends_on:
      - backend
